# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil_perfil_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ('creado',), 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
