# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170913_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
