# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171019_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
