# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171026_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='perfil_usuario',
            field=models.CharField(blank=True, choices=[(b'GAP Administrador', b'GAP Administrador'), (b'GAP Visitante', b'GAP Visitante'), (b'NI Ingeniero', b'NI Ingeniero'), (b'NI Asignador', b'NI Asignador'), (b'NPO Ingeniero', b'NPO Ingeniero'), (b'NPO Asignador', b'NPO Asignador'), (b'FM Lider', b'FM Lider'), (b'FM Permisos', b'FM Permisos'), (b'FM Supervisor', b'FM Supervisor')], max_length=255, null=True),
        ),
    ]
