# Generated by Django 2.0 on 2018-01-10 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20171217_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='par',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='par', to=settings.AUTH_USER_MODEL),
        ),
    ]
