# Generated by Django 2.0 on 2018-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_perfil_par'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ('creado',), 'permissions': (('perm_gap_administrador', 'Permisos para GAP Administrador'), ('perm_gap_visitante', 'Permisos para GAP Visitante'), ('perm_ni_ingeniero', 'Permisos para NI Ingeniero'), ('perm_ni_asignador', 'Permisos para NI Asignador'), ('perm_npo_ingeniero', 'Permisos para NPO Ingeniero'), ('perm_npo_asignador', 'Permisos para NPO Asignador'), ('perm_fm_lider', 'Permisos para FM Lider'), ('perm_fm_permisos', 'Permisos para FM Permisos'), ('perm_fm_supervisor', 'Permisos para FM Supervisor'), ('perm_gap_monitoreo', 'Permisos para GAP Monitoreo')), 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='perfil_usuario',
            field=models.CharField(blank=True, choices=[('GAP Administrador', 'GAP Administrador'), ('GAP Visitante', 'GAP Visitante'), ('NI Ingeniero', 'NI Ingeniero'), ('NI Asignador', 'NI Asignador'), ('NPO Ingeniero', 'NPO Ingeniero'), ('NPO Asignador', 'NPO Asignador'), ('FM Lider', 'FM Lider'), ('FM Permisos', 'FM Permisos'), ('FM Supervisor', 'FM Supervisor'), ('GAP Monitoreo', 'GAP Monitoreo')], max_length=255, null=True),
        ),
    ]
