# Generated by Django 2.0 on 2018-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_auto_20180113_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionfallainstalacion',
            name='wp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacionfallaintegracion',
            name='wp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacionrequierevisita',
            name='wp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
