# Generated by Django 2.0 on 2018-02-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_perfil_par'),
        ('estaciones', '0013_estacion_numero_actividades'),
        ('actividades', '0046_auto_20180202_0850'),
        ('asignaciones', '0040_auto_20180209_1326'),
        ('notificaciones', '0004_notificacionfallaajustepotencia_notificacionfallacambiodiseno_notificacionfallacomportamientoesperad'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionFallaComportamientoPrevio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('service_supplier', models.CharField(blank=True, choices=[('DECOM', 'DECOM'), ('INGETEL', 'INGETEL'), ('ENECON', 'ENECON'), ('NEXPRO', 'NEXPRO'), ('JANACOR', 'JANACOR'), ('UNION', 'UNION'), ('OPTIMACOM', 'OPTIMACOM'), ('DELTEC', 'DELTEC'), ('FIBRATERRA', 'FIBRATERRA'), ('ADSM', 'ADSM'), ('SERVINTELCO', 'SERVINTELCO'), ('EZENTIS', 'EZENTIS'), ('SITCOM', 'SITCOM'), ('INGYTELCOM', 'INGYTELCOM'), ('SAI', 'SAI'), ('GAMMA', 'GAMMA'), ('PACIFIC ENERGY', 'PACIFIC ENERGY'), ('FUREL', 'FUREL'), ('NEOSTAR', 'NEOSTAR'), ('DASCON', 'DASCON'), ('ATENA', 'ATENA'), ('ZOOM', 'ZOOM'), ('LINEA', 'LINEA'), ('WISECA', 'WISECA'), ('REDES Y SERVICIOS', 'REDES Y SERVICIOS'), ('NESITELCO', 'NESITELCO'), ('NOKIA', 'NOKIA'), ('OSC', 'OSC'), ('WB INGENIERIA', 'WB INGENIERIA'), ('VOLUMEN', 'VOLUMEN'), ('INTELCOM', 'INTELCOM'), ('ASECONES', 'ASECONES'), ('SOI', 'SOI'), ('CONECTAR', 'CONECTAR'), ('IDT', 'IDT'), ('TECHMAHINDRA', 'TECHMAHINDRA'), ('ADS INTEGRAL', 'ADS INTEGRAL'), ('APPLUS', 'APPLUS'), ('CLARO', 'CLARO'), ('OIN (CLARO)', 'OIN (CLARO)'), ('SFERA', 'SFERA'), ('MSI', 'MSI')], max_length=255, null=True)),
                ('banda', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('escenario', models.CharField(blank=True, max_length=255, null=True)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_falla_comportamiento_previo', to='actividades.Actividad')),
                ('asignacion_ni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_falla_comportamiento_previo', to='asignaciones.AsignacionNi')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_falla_comportamiento_previo', to='estaciones.Estacion')),
                ('ni_ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_falla_comportamiento_previo', to='users.Perfil')),
            ],
            options={
                'verbose_name': 'notificacion falla comportamiento previo',
                'verbose_name_plural': 'notificaciones falla comportamiento previo',
                'ordering': ('creado',),
            },
        ),
    ]
