# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20170913_2204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.IntegerField(blank=True, null=True)),
                ('id_notificacion_noc', models.IntegerField(blank=True, null=True)),
                ('banda', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnologia', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_wp_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('escenario', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ingreso_onair', models.DateField(blank=True, null=True)),
                ('regional', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('realtifinish', models.DateField(blank=True, null=True)),
                ('fecha_integracion', models.DateField(blank=True, null=True)),
                ('tipo_gap', models.CharField(blank=True, choices=[(b'GAP On Air', b'GAP On Air'), (b'GAP Integracion', b'GAP Integracion'), (b'Produccion', b'Produccion')], max_length=255, null=True)),
                ('tx_df_confirmado', models.CharField(blank=True, max_length=255, null=True)),
                ('notificaciones', models.CharField(blank=True, choices=[(b'NOTIFICADO NOC', b'NOTIFICADO NOC'), (b'NOTIFICADO NOC GAP', b'NOTIFICADO NOC GAP'), (b'PENDIENTE INTEGRAR', b'PENDIENTE INTEGRAR'), (b'PENDIENTE NOTIFICAR', b'PENDIENTE NOTIFICAR'), (b'PENDIENTE NOTIFICAR RSH', b'PENDIENTE NOTIFICAR RSH'), (b'PENDIENTE NOTIFICAR OV LTE CE', b'PENDIENTE NOTIFICAR OV LTE CE'), (b'PENDIENTE NOTIFICAR SRAN', b'PENDIENTE NOTIFICAR SRAN'), (b'PENDIENTE INTEGRAR SRAN', b'PENDIENTE INTEGRAR SRAN'), (b'INTEGRADO GAP', b'INTEGRADO GAP')], max_length=255, null=True)),
                ('estado_noc', models.CharField(blank=True, choices=[(b'Produccion', b'Produccion'), (b'Seguimiento FO', b'Seguimiento FO'), (b'Escalado a Implementacion', b'Escalado a Implementacion'), (b'Escalado a Grupo Calidad', b'Escalado a Grupo Calidad'), (b'Escalado a RF', b'Escalado a RF'), (b'En Reporte QANOC', b'En Reporte QANOC')], max_length=255, null=True)),
                ('subestado_noc', models.CharField(blank=True, choices=[(b'Alarmas de HW', b'Alarmas de HW'), (b'Alarmas de Rx Sistema Radiante', b'Alarmas de Rx Sistema Radiante'), (b'Alarmas de TX', b'Alarmas de TX'), (b'Alto RTWP', b'Alto RTWP'), (b'Degradacion KPI', b'Degradacion KPI'), (b'Error Comisionamiento BTS', b'Error Comisionamiento BTS'), (b'Error Configuracion Acceso', b'Error Configuracion Acceso'), (b'Error de Instalacion', b'Error de Instalacion'), (b'Pendiente CRQ', b'Pendiente CRQ'), (b'Pendiente DF', b'Pendiente DF'), (b'Pendiente Evidencias', b'Pendiente Evidencias'), (b'Pendiente Pruebas Alarmas', b'Pendiente Pruebas Alarmas'), (b'Pendiente Sitio Limpio', b'Pendiente Sitio Limpio'), (b'Pendiente Tareas Remedy', b'Pendiente Tareas Remedy'), (b'Pendiente Testgestion', b'Pendiente Testgestion'), (b'Perdida de Paquetes', b'Perdida de Paquetes'), (b'Produccion', b'Produccion'), (b'Revision Parcial', b'Revision Parcial'), (b'Seguimiento FO', b'Seguimiento FO'), (b'Sin Trafico', b'Sin Trafico'), (b'Sitio Fuera de Servicio', b'Sitio Fuera de Servicio'), (b'Sin Conexion Remota', b'Sin Conexion Remota')], max_length=255, null=True)),
                ('degradacion', models.TextField(blank=True, null=True)),
                ('fecha_asignacion_npo', models.DateField(blank=True, null=True)),
                ('fecha_primera_respuesta_npo', models.DateField(blank=True, null=True)),
                ('fecha_ultima_respuesta_npo', models.DateField(blank=True, null=True)),
                ('fecha_concepto_npo', models.DateField(blank=True, null=True)),
                ('concepto_npo', models.TextField(blank=True, null=True)),
                ('responsable_npo', models.CharField(blank=True, choices=[(b'Richard Veintimilla', b'Richard Veintimilla'), (b'Cesar Rojas', b'Cesar Rojas'), (b'Jairo Polo', b'Jairo Polo'), (b'Jaime Figueroa', b'Jaime Figueroa'), (b'Raul Perez', b'Raul Perez'), (b'Esteban Gallegos', b'Esteban Gallegos'), (b'Diego Estrella', b'Diego Estrella')], max_length=255, null=True)),
                ('celular_npo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable_actual', models.CharField(blank=True, choices=[(b'NI', b'NI'), (b'NPO', b'NPO'), (b'Optimizacion', b'Optimizacion')], max_length=255, null=True)),
                ('impacto_degradacion', models.CharField(blank=True, choices=[(b'Leve', b'Leve'), (b'Grave', b'Grave')], max_length=255, null=True)),
                ('requiere_visita', models.CharField(blank=True, choices=[(b'OK', b'OK'), (b'NOK', b'NOK')], max_length=255, null=True)),
                ('fecha_fc_visita', models.DateField(blank=True, null=True)),
                ('id_siteaccess', models.CharField(blank=True, max_length=255, null=True)),
                ('precheck', models.CharField(blank=True, choices=[(b'OK', b'OK'), (b'NOK', b'NOK')], max_length=255, null=True)),
                ('visita_supervisor', models.CharField(blank=True, choices=[(b'Fabian Barbosa', b'Fabian Barbosa'), (b'Andres Cardenas', b'Andres Cardenas'), (b'Jonathan Cuervo', b'Jonathan Cuervo'), (b'Carlos Santos', b'Carlos Santos'), (b'Jimmy Sepulveda', b'Jimmy Sepulveda'), (b'Wilson Bohorquez', b'Wilson Bohorquez'), (b'Mario Fiallo', b'Mario Fiallo'), (b'Hober Sanchez', b'Hober Sanchez'), (b'Leonardo Alarcon', b'Leonardo Alarcon'), (b'Ruben Alvarado', b'Ruben Alvarado'), (b'Diego Medina', b'Diego Medina'), (b'Jhon Uparela', b'Jhon Uparela'), (b'Carlos Funeme', b'Carlos Funeme'), (b'Yony Sanchez', b'Yony Sanchez'), (b'Ramon montagut', b'Ramon montagut'), (b'Richard Luna', b'Richard Luna'), (b'Jolman Castillo', b'Jolman Castillo'), (b'Manuel Garcia', b'Manuel Garcia')], max_length=255, null=True)),
                ('celular_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('integrador', models.CharField(blank=True, choices=[(b'Carol Rodriguez', b'Carol Rodriguez'), (b'Arnold Guzman', b'Arnold Guzman'), (b'Jhon Davis Naranjo', b'Jhon Davis Naranjo'), (b'Lorena Sotomonte', b'Lorena Sotomonte'), (b'Gabriel Valdez', b'Gabriel Valdez'), (b'Paolo Alvaran', b'Paolo Alvaran'), (b'Victor Garcia', b'Victor Garcia'), (b'Ivan Barriga', b'Ivan Barriga')], max_length=255, null=True)),
                ('celular_integrador', models.CharField(blank=True, max_length=255, null=True)),
                ('concepto_ni', models.TextField(blank=True, null=True)),
                ('fecha_concepto_ni', models.DateField(blank=True, null=True)),
                ('enviado_seguimiento', models.CharField(blank=True, choices=[(b'OK', b'OK'), (b'NOK', b'NOK')], max_length=255, null=True)),
                ('tipo_intervencion', models.CharField(blank=True, choices=[(b'Local', b'Local'), (b'Remoto', b'Remoto')], max_length=255, null=True)),
                ('requiere_hw', models.CharField(blank=True, choices=[(b'OK', b'OK'), (b'NOK', b'NOK')], max_length=255, null=True)),
                ('cantidad_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='estaciones.Estacion')),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'permissions': (('perm_gap_administrador', 'Permisos para GAP Administrador'), ('perm_ni_ingeniero', 'Permisos para NI Ingeniero'), ('perm_ni_asignador', 'Permisos para NI Asignador'), ('perm_npo_ingeniero', 'Permisos para NPO Ingeniero'), ('perm_npo_asignador', 'Permisos para NPO Asignador'), ('perm_fm_lider', 'Permisos para FM Lider'), ('perm_fm_permisos', 'Permisos para FM Permisos')),
            },
        ),
        migrations.CreateModel(
            name='ConceptoNi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='concepto_ni/imagen')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_ni', to='actividades.Actividad')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_ni', to='users.Perfil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_ni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'concepto ni',
                'verbose_name_plural': 'conceptos ni',
            },
        ),
        migrations.CreateModel(
            name='ConceptoNpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='concepto_npo/imagen')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_npo', to='actividades.Actividad')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_npo', to='users.Perfil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_npo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'concepto npo',
                'verbose_name_plural': 'conceptos npo',
            },
        ),
        migrations.CreateModel(
            name='Degradacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degradaciones', to='actividades.Actividad')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degradaciones', to='users.Perfil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degradaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'degradacion',
                'verbose_name_plural': 'degradaciones',
            },
        ),
    ]
