# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoni',
            name='wp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptonpo',
            name='wp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='degradacion',
            name='wp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
