# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
        ('actividades', '0003_auto_20170922_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoni',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_ni', to='estaciones.Estacion'),
        ),
        migrations.AddField(
            model_name='conceptonpo',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_npo', to='estaciones.Estacion'),
        ),
        migrations.AddField(
            model_name='degradacion',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degradaciones', to='estaciones.Estacion'),
        ),
        migrations.AlterField(
            model_name='conceptoni',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_ni', related_query_name='conceptos_ni', to='actividades.Actividad'),
        ),
        migrations.AlterField(
            model_name='conceptonpo',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_npo', related_query_name='conceptos_npo', to='actividades.Actividad'),
        ),
        migrations.AlterField(
            model_name='degradacion',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degradaciones', related_query_name='degradaciones', to='actividades.Actividad'),
        ),
    ]
