# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_auto_20170926_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='integrador',
            field=models.CharField(blank=True, choices=[(b'Carol Rodriguez', b'Carol Rodriguez'), (b'Arnold Guzman', b'Arnold Guzman'), (b'Jhon Davis Naranjo', b'Jhon Davis Naranjo'), (b'Lorena Sotomonte', b'Lorena Sotomonte'), (b'Gabriel Valdez', b'Gabriel Valdez'), (b'Paolo Alvaran', b'Paolo Alvaran'), (b'Victor Garcia', b'Victor Garcia'), (b'Ivan Barriga', b'Ivan Barriga'), (b'Jorge Romero', b'Jorge Romero')], max_length=255, null=True),
        ),
    ]
