# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170913_2204'),
        ('actividades', '0005_auto_20170926_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ingeniero_ni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_ingeniero_ni', to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ingeniero_npo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_ingeniero_npo', to='users.Perfil'),
        ),
    ]
