# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_auto_20170926_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='agrupador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
