# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_actividad_agrupador'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
