# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170913_2204'),
        ('actividades', '0008_actividad_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='ingeniero_ni',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='ingeniero_npo',
        ),
        migrations.AddField(
            model_name='actividad',
            name='ni_ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_ni_ingeniero', to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='npo_ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_npo_ingeniero', to='users.Perfil'),
        ),
    ]
