# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_auto_20170928_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tx_df_confirmado',
        ),
        migrations.AddField(
            model_name='actividad',
            name='grupo_gap',
            field=models.CharField(blank=True, choices=[(b'GAP1', b'GAP1'), (b'GAP2', b'GAP2')], max_length=255, null=True),
        ),
    ]
