# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_auto_20171005_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='celular_integrador',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='celular_npo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='concepto_ni',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='concepto_npo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='degradacion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='enviado_seguimiento',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_asignacion_npo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_concepto_ni',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_concepto_npo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_primera_respuesta_npo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_ultima_respuesta_npo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='integrador',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='ni_ingeniero',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='notificaciones',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='npo_ingeniero',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='regional',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='requiere_visita',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='responsable_npo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='tecnologia',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='tipo_gap',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='tipo_intervencion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='subestado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
