# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_auto_20171008_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='subestado',
            field=models.BooleanField(default=False),
        ),
    ]
