# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0019_auto_20171016_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ('creado',), 'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
    ]
