# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0021_auto_20171017_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='grupo_gap',
            field=models.CharField(blank=True, choices=[(b'GAP1', b'GAP1'), (b'GAP2', b'GAP2'), (b'ZTE', b'ZTE')], max_length=255, null=True),
        ),
    ]
