# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0024_auto_20171018_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='po_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ss_tbs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
