# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0026_auto_20171018_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ('creado',), 'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ss_tbs',
            field=models.CharField(blank=True, choices=[(b'UNION', b'UNION'), (b'CONSTRUTECH', b'CONSTRUTECH'), (b'FIBRATERRA', b'FIBRATERRA'), (b'SAI', b'SAI'), (b'SERVINTELCO', b'SERVINTELCO'), (b'INGYTELCOM', b'INGYTELCOM'), (b'REDES Y SERVICIOS', b'REDES Y SERVICIOS'), (b'ZOOM', b'ZOOM'), (b'INGYTELCOM', b'INGYTELCOM'), (b'INGETEL', b'INGETEL'), (b'ADSM', b'ADSM'), (b'GAMMA', b'GAMMA')], max_length=255, null=True),
        ),
    ]
