# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0029_auto_20171025_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='celular_supervisor',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='id_siteaccess',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='precheck',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='responsable_actual',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='visita_supervisor',
        ),
        migrations.AddField(
            model_name='actividad',
            name='ni_fm_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='npo_fm_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
