# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0030_auto_20171025_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ni_fm_supervisor',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='npo_fm_supervisor',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
