# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0031_auto_20171025_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='wp',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
