# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0032_auto_20171030_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degradacion',
            name='user',
        ),
    ]
