# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0033_remove_degradacion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_trabajo',
            field=models.CharField(blank=True, choices=[(b'LTE Overlay', b'LTE Overlay'), (b'Tercera Portadora', b'Tercera Portadora'), (b'3G Huawei Overlay', b'3G Huawei Overlay'), (b'Sitio Nuevo 3G', b'Sitio Nuevo 3G'), (b'Sitio Nuevo 2G PE', b'Sitio Nuevo 2G PE'), (b'Sitio Nuevo LTE', b'Sitio Nuevo LTE'), (b'Sector Expansion', b'Sector Expansion'), (b'Sitio Nuevo 3G PE', b'Sitio Nuevo 3G PE'), (b'3G Overlay', b'3G Overlay'), (b'Cambio de Jumpers y Breaker_CP', b'Cambio de Jumpers y Breaker_CP'), (b'Cambio HW para MC_CP', b'Cambio HW para MC_CP'), (b'Channel Element_CP', b'Channel Element_CP'), (b'Adecuaciones LTE', b'Adecuaciones LTE'), (b'Cuarta Portadora', b'Cuarta Portadora'), (b'Cambio HW para MC', b'Cambio HW para MC'), (b'Modernizacion Multiradio', b'Modernizacion Multiradio'), (b'Channel Element_MMR', b'Channel Element_MMR'), (b'Segundo Nodo', b'Segundo Nodo'), (b'Channel Element_5P', b'Channel Element_5P'), (b'Reubicacion', b'Reubicacion'), (b'Sitio Nuevo LTE PE', b'Sitio Nuevo LTE PE'), (b'Sector Expansion Huawei', b'Sector Expansion Huawei'), (b'Cambio de Jumpers y RRU', b'Cambio de Jumpers y RRU'), (b'Cambio HW para MC Huawei', b'Cambio HW para MC Huawei'), (b'Swap', b'Swap'), (b'Cambio HW LTE', b'Cambio HW LTE'), (b'Sitio Nuevo 3G/LTE Temporal', b'Sitio Nuevo 3G/LTE Temporal'), (b'Cambio de Jumpers y Breaker', b'Cambio de Jumpers y Breaker'), (b'Cambio de Jumpers y Breaker_5P', b'Cambio de Jumpers y Breaker_5P'), (b'Adecuaciones SE', b'Adecuaciones SE'), (b'LTE Huawei Overlay', b'LTE Huawei Overlay'), (b'Adecuaciones LTE Huawei', b'Adecuaciones LTE Huawei'), (b'Channel Element', b'Channel Element'), (b'Cambio HW para MC_5P', b'Cambio HW para MC_5P'), (b'Cambio HW para MC_5P y RF', b'Cambio HW para MC_5P y RF'), (b'Swap Antenas Capa 4-5', b'Swap Antenas Capa 4-5'), (b'Channel Element + Upgrade Modulos RF', b'Channel Element + Upgrade Modulos RF'), (b'Channel Element_5P y RF', b'Channel Element_5P y RF'), (b'Cuarta Portadora Huawei', b'Cuarta Portadora Huawei'), (b'Tercera Portadora Huawei', b'Tercera Portadora Huawei'), (b'Adecuaciones Overlay', b'Adecuaciones Overlay'), (b'Adecuacion para LTE 1900Mhz', b'Adecuacion para LTE 1900Mhz'), (b'Upgrade Modulos RF', b'Upgrade Modulos RF'), (b'Cambio Feeder a Fibra', b'Cambio Feeder a Fibra'), (b'RF Sharing a Dedicado', b'RF Sharing a Dedicado'), (b'Reubicacion Equipos', b'Reubicacion Equipos'), (b'Cambio HW', b'Cambio HW'), (b'Modernizacion Concurrente', b'Modernizacion Concurrente'), (b'Cambio de Jumpers', b'Cambio de Jumpers')], max_length=255, null=True),
        ),
    ]
