# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0035_auto_20171102_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='wp',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
