# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0038_actividad_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='responsable',
            field=models.CharField(blank=True, choices=[(b'GAP1', b'GAP1'), (b'GAP2', b'GAP2'), (b'ZTE', b'ZTE')], editable=False, max_length=255, null=True),
        ),
    ]
