# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0040_remove_actividad_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ni_estado_solicitud_hw',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
