# Generated by Django 2.0 on 2017-12-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0042_auto_20171217_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='npo_posible_causa',
            new_name='ni_origen_falla',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='cantidad_hw',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='requiere_hw',
        ),
    ]
