# Generated by Django 2.0 on 2018-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0044_auto_20180109_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='solver',
        ),
        migrations.AddField(
            model_name='actividad',
            name='ni_solver',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
