# Generated by Django 2.0 on 2018-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0047_auto_20180214_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado_noc',
            field=models.CharField(blank=True, choices=[('Produccion', 'Produccion'), ('Escalado a Implementacion', 'Escalado a Implementacion'), ('Escalado a Grupo Calidad', 'Escalado a Grupo Calidad'), ('Escalado a RF', 'Escalado a RF'), ('Escalado a OyM', 'Escalado a OyM'), ('Escalado a GDRT', 'Escalado a GDRT'), ('Escalado Control Cambios', 'Escalado Control Cambios'), ('Seguimiento 12h', 'Seguimiento 12h'), ('Seguimiento 24h', 'Seguimiento 24h'), ('Seguimiento 36h', 'Seguimiento 36h'), ('PreCheck', 'PreCheckC'), ('Pendiente Remedy', 'Pendiente Remedy'), ('Stand By', 'Stand By'), ('Rollback', 'Rollback'), ('Suspendido', 'Suspendido')], max_length=255, null=True),
        ),
    ]
