# Generated by Django 2.0 on 2018-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0050_auto_20180301_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='field_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
