# Generated by Django 2.0 on 2018-01-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_perfil_par'),
        ('estaciones', '0011_auto_20171224_1320'),
        ('actividades', '0045_auto_20180109_1128'),
        ('incidentes', '0002_incidenteni_asignar_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioNi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('subestado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_ni', to='actividades.Actividad')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_ni', to='estaciones.Estacion')),
                ('incidente_ni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_ni', to='incidentes.IncidenteNi')),
                ('ni_ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_ni', to='users.Perfil')),
            ],
            options={
                'verbose_name': 'comentario ni',
                'verbose_name_plural': 'comentarios ni',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='ComentarioNpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('subestado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_npo', to='actividades.Actividad')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_npo', to='estaciones.Estacion')),
                ('incidente_npo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_npo', to='incidentes.IncidenteNpo')),
                ('npo_ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_npo', to='users.Perfil')),
            ],
            options={
                'verbose_name': 'comentario npo',
                'verbose_name_plural': 'comentarios npo',
                'ordering': ('creado',),
            },
        ),
    ]
