# Generated by Django 2.0 on 2018-01-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0045_auto_20180109_1128'),
        ('users', '0014_perfil_par'),
        ('estaciones', '0011_auto_20171224_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteNi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('estado_incidente', models.CharField(blank=True, choices=[('', '---------'), ('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=255, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('subestado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_ni', to='actividades.Actividad')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_ni', to='estaciones.Estacion')),
                ('ni_ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_ni', to='users.Perfil')),
            ],
            options={
                'verbose_name': 'incidente ni',
                'verbose_name_plural': 'incidentes ni',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='IncidenteNpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('estado_incidente', models.CharField(blank=True, choices=[('', '---------'), ('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=255, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('subestado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_npo', to='actividades.Actividad')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_npo', to='estaciones.Estacion')),
                ('npo_ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_npo', to='users.Perfil')),
            ],
            options={
                'verbose_name': 'incidente npo',
                'verbose_name_plural': 'incidentes npo',
                'ordering': ('creado',),
            },
        ),
    ]
