# Generated by Django 2.0 on 2018-01-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_incidenteni_asignar_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenteni',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='incidentenpo',
            name='comentario',
        ),
    ]
