# Generated by Django 2.0 on 2018-03-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0051_actividad_field_manager'),
        ('estaciones', '0013_estacion_numero_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado_alerta', models.CharField(blank=True, choices=[('', '---------'), ('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=255, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('subestado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='actividades.Actividad')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ('creado',),
            },
        ),
    ]
