# Generated by Django 2.0 on 2018-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Normalizacion', 'Normalizacion')], max_length=255, null=True),
        ),
    ]
