# -*- coding: utf-8 -*-

""" TIPO_FALLA_CHOICES  """
TIPO_FALLA_CHOICES = (
    ('', '---------'),
    ('Instalacion', 'Instalacion'),
    ('Software', 'Software'),
    ('Hardware', 'Hardware'),
    ('Datafill', 'Datafill'),
    ('Ajuste Potencia', 'Ajuste Potencia'),
    ('Integracion', 'Integracion'),
    ('Interferencia externa', 'Interferencia externa'),
    ('Cambio diseno', 'Cambio diseno'),
    ('Mal rechazo', 'Mal rechazo'),
    ('TX', 'TX'),
    ('Falla Externa', 'Falla Externa'),
    ('Falla TSS', 'Falla TSS'),
    ('Ajuste Adyacencias', 'Ajuste Adyacencias'),
)

""" SERVICE_SUPPLIER_CHOICES  """
SERVICE_SUPPLIER_CHOICES = (
    ('DECOM', 'DECOM'),
    ('INGETEL', 'INGETEL'),
    ('ENECON', 'ENECON'),
    ('NEXPRO', 'NEXPRO'),
    ('JANACOR', 'JANACOR'),
    ('UNION', 'UNION'),
    ('OPTIMACOM', 'OPTIMACOM'),
    ('DELTEC', 'DELTEC'),
    ('FIBRATERRA', 'FIBRATERRA'),
    ('ADSM', 'ADSM'),
    ('SERVINTELCO', 'SERVINTELCO'),
    ('EZENTIS', 'EZENTIS'),
    ('SITCOM', 'SITCOM'),
    ('INGYTELCOM', 'INGYTELCOM'),
    ('SAI', 'SAI'),
    ('GAMMA', 'GAMMA'),
    ('PACIFIC ENERGY', 'PACIFIC ENERGY'),
    ('FUREL', 'FUREL'),
    ('NEOSTAR', 'NEOSTAR'),
    ('DASCON', 'DASCON'),
    ('ATENA', 'ATENA'),
    ('ZOOM', 'ZOOM'),
    ('LINEA', 'LINEA'),
    ('WISECA', 'WISECA'),
    ('REDES Y SERVICIOS', 'REDES Y SERVICIOS'),
    ('NESITELCO', 'NESITELCO'),
    ('NOKIA', 'NOKIA'),
    ('OSC', 'OSC'),
    ('WB INGENIERIA', 'WB INGENIERIA'),
    ('VOLUMEN', 'VOLUMEN'),
    ('INTELCOM', 'INTELCOM'),
    ('ASECONES', 'ASECONES'),
    ('SOI', 'SOI'),
    ('CONECTAR', 'CONECTAR'),
    ('IDT', 'IDT'),
    ('TECHMAHINDRA', 'TECHMAHINDRA'),
    ('ADS INTEGRAL', 'ADS INTEGRAL'),
    ('APPLUS', 'APPLUS'),
    ('CLARO', 'CLARO'),
    ('OIN (CLARO)', 'OIN (CLARO)'),
    ('SFERA', 'SFERA'),
    ('MSI', 'MSI'),
    ('YINDA', 'YINDA'),
    ('CELPLAN', 'CELPLAN'),
    ('RSE', 'RSE'),
    ('INMEL', 'INMEL'),
    ('CINCO', 'CINCO'),
    ('OPG', 'OPG'),
    ('NEWICT', 'NEWICT'),
    ('CAT', 'CAT'),
    ('STI', 'STI'),
    ('PRECOOM', 'PRECOOM'),
)
