# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0003_auto_20170928_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptoni',
            old_name='perfil',
            new_name='ni_ingeniero',
        ),
        migrations.RenameField(
            model_name='conceptonpo',
            old_name='perfil',
            new_name='npo_ingeniero',
        ),
        migrations.RemoveField(
            model_name='conceptoni',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conceptonpo',
            name='user',
        ),
    ]
