# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0004_auto_20170929_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptoni',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_ni', to='actividades.Actividad'),
        ),
        migrations.AlterField(
            model_name='conceptonpo',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_npo', to='actividades.Actividad'),
        ),
    ]
