# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0005_auto_20171009_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoni',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptoni',
            name='subestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptonpo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptonpo',
            name='subestado',
            field=models.BooleanField(default=False),
        ),
    ]
