# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0006_auto_20171012_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptoni',
            name='wp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptonpo',
            name='wp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
