# Generated by Django 2.0 on 2018-02-23 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0041_auto_20180223_1810'),
        ('actividades', '0048_auto_20180215_1551'),
        ('users', '0014_perfil_par'),
        ('estaciones', '0013_estacion_numero_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('service_supplier', models.CharField(blank=True, choices=[('DECOM', 'DECOM'), ('INGETEL', 'INGETEL'), ('ENECON', 'ENECON'), ('NEXPRO', 'NEXPRO'), ('JANACOR', 'JANACOR'), ('UNION', 'UNION'), ('OPTIMACOM', 'OPTIMACOM'), ('DELTEC', 'DELTEC'), ('FIBRATERRA', 'FIBRATERRA'), ('ADSM', 'ADSM'), ('SERVINTELCO', 'SERVINTELCO'), ('EZENTIS', 'EZENTIS'), ('SITCOM', 'SITCOM'), ('INGYTELCOM', 'INGYTELCOM'), ('SAI', 'SAI'), ('GAMMA', 'GAMMA'), ('PACIFIC ENERGY', 'PACIFIC ENERGY'), ('FUREL', 'FUREL'), ('NEOSTAR', 'NEOSTAR'), ('DASCON', 'DASCON'), ('ATENA', 'ATENA'), ('ZOOM', 'ZOOM'), ('LINEA', 'LINEA'), ('WISECA', 'WISECA'), ('REDES Y SERVICIOS', 'REDES Y SERVICIOS'), ('NESITELCO', 'NESITELCO'), ('NOKIA', 'NOKIA'), ('OSC', 'OSC'), ('WB INGENIERIA', 'WB INGENIERIA'), ('VOLUMEN', 'VOLUMEN'), ('INTELCOM', 'INTELCOM'), ('ASECONES', 'ASECONES'), ('SOI', 'SOI'), ('CONECTAR', 'CONECTAR'), ('IDT', 'IDT'), ('TECHMAHINDRA', 'TECHMAHINDRA'), ('ADS INTEGRAL', 'ADS INTEGRAL'), ('APPLUS', 'APPLUS'), ('CLARO', 'CLARO'), ('OIN (CLARO)', 'OIN (CLARO)'), ('SFERA', 'SFERA'), ('MSI', 'MSI'), ('YINDA', 'YINDA')], max_length=255, null=True)),
                ('banda', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('escenario', models.CharField(blank=True, max_length=255, null=True)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('tipo_falla', models.CharField(blank=True, choices=[('', '---------'), ('Instalacion', 'Instalacion'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Datafill', 'Datafill'), ('Ajuste Potencia', 'Ajuste Potencia'), ('Integracion', 'Integracion'), ('Interferencia externa', 'Interferencia externa'), ('Cambio diseno', 'Cambio diseno'), ('Mal rechazo', 'Mal rechazo'), ('TX', 'TX'), ('Comportamiento esperado', 'Comportamiento esperado'), ('Comportamiento previo', 'Comportamiento previo'), ('Ajuste Adyacencias', 'Ajuste Adyacencias')], max_length=255, null=True)),
                ('estado', models.BooleanField(default=False, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='actividades.Actividad')),
                ('asignacion_ni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='asignaciones.AsignacionNi')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='estaciones.Estacion')),
                ('ni_ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='users.Perfil')),
            ],
            options={
                'verbose_name': 'falla',
                'verbose_name_plural': 'fallas',
                'ordering': ('creado',),
            },
        ),
    ]
