# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.IntegerField(blank=True, null=True)),
                ('agrupador', models.CharField(blank=True, max_length=255, null=True)),
                ('estacion', models.CharField(blank=True, max_length=255, null=True)),
                ('banda', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('escenario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_integracion', models.DateField(blank=True, null=True)),
                ('tipo_gap', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_trabajo_noc', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_noc', models.CharField(blank=True, max_length=255, null=True)),
                ('subestado_noc', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable_ni', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_ni', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_asignacion_ni', models.DateField(blank=True, null=True)),
                ('requiere_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable_npo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_npo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_asignacion_npo', models.DateField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_fc_visita', models.DateField(blank=True, null=True)),
                ('id_siteaccess', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'reporte actividad',
                'verbose_name_plural': 'reporte actividades',
            },
        ),
    ]
