# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170913_2204'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteactividad',
            name='concepto_ni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteactividad',
            name='concepto_npo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteactividad',
            name='gap_administrador',
            field=models.ManyToManyField(to='users.Perfil'),
        ),
    ]
