# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20171005_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteactividad',
            name='grupo_gap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
