# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reporteactividad_grupo_gap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteactividad',
            name='tipo_gap',
        ),
        migrations.AddField(
            model_name='reporteactividad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteactividad',
            name='regional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteactividad',
            name='tipo_intervencion_ni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteactividad',
            name='tipo_intervencion_npo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteactividad',
            name='valor_wp_eur',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True),
        ),
    ]
