# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_auto_20171009_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteactividad',
            name='posible_causa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
