# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('regional', models.CharField(choices=[(b'Centro', b'Centro'), (b'Costa', b'Costa'), (b'NorOccidente', b'NorOccidente'), (b'NorOriente', b'NorOriente'), (b'SurOccidente', b'SurOccidente')], max_length=255)),
                ('ciudad', models.CharField(choices=[(b'Bogota', b'Bogota'), (b'Cali', b'Cali'), (b'Medellin', b'Medellin'), (b'Bucaramanga', b'Bucaramanga'), (b'Barranquilla', b'Barranquilla')], max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'estacion',
                'verbose_name_plural': 'estaciones',
            },
        ),
    ]
