# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0003_auto_20171018_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='responsable',
            field=models.CharField(blank=True, choices=[(b'GAP1', b'GAP1'), (b'GAP2', b'GAP2'), (b'ZTE', b'ZTE')], max_length=255, null=True),
        ),
    ]
