# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0007_estacion_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='prioridad',
            field=models.CharField(blank=True, choices=[(b'P1', b'P1')], max_length=255, null=True),
        ),
    ]
