# Generated by Django 2.0 on 2017-12-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0008_auto_20171115_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='ciudad',
            field=models.CharField(choices=[('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlantico', 'Atlantico'), ('Barranquilla', 'Barranquilla'), ('Valle', 'Valle'), ('Bogota', 'Bogota'), ('Bolivar', 'Bolivar'), ('Boyaca', 'Boyaca'), ('Bucaramanga', 'Bucaramanga'), ('Caldas', 'Caldas'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Chia', 'Chia'), ('Choco', 'Choco'), ('Cordoba', 'Cordoba'), ('Cucuta', 'Cucuta'), ('Cundinamarca', 'Cundinamarca'), ('Girardot', 'Girardot'), ('Guajira', 'Guajira'), ('Huila', 'Huila'), ('Ibague', 'Ibague'), ('Magdalena', 'Magdalena'), ('Medellin', 'Medellin'), ('Meta', 'Meta'), ('Norte de Santander', 'Norte de Santander'), ('Pasto', 'Pasto'), ('Pereira', 'Pereira'), ('Quindio', 'Quindio'), ('Risaralda', 'Risaralda'), ('Sincelejo', 'Sincelejo'), ('Santander', 'Santander'), ('Soacha', 'Soacha'), ('Sucre', 'Sucre'), ('Tolima', 'Tolima'), ('Tulua', 'Tulua'), ('Villavicencio', 'Villavicencio'), ('Putumayo', 'Putumayo'), ('Manizales', 'Manizales'), ('Valledupar', 'Valledupar'), ('Santa Marta', 'Santa Marta'), ('Zipaquira', 'Zipaquira'), ('Buenaventura', 'Buenaventura'), ('Casanare', 'Casanare'), ('Barranca', 'Barranca'), ('Ubate', 'Ubate'), ('Fusagasuga', 'Fusagasuga'), ('Duitama', 'Duitama'), ('Sogamoso', 'Sogamoso'), ('Tunja', 'Tunja'), ('Yopal', 'Yopal'), ('Florencia', 'Florencia'), ('Armenia', 'Armenia'), ('Valle del Cauca', 'Valle del Cauca'), ('Jamundi', 'Jamundi')], max_length=255),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('P1', 'P1')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='regional',
            field=models.CharField(choices=[('Centro', 'Centro'), ('Costa', 'Costa'), ('Nor Occidente', 'Nor Occidente'), ('Nor Oriente', 'Nor Oriente'), ('Sur Occidente', 'Sur Occidente')], max_length=255),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='responsable',
            field=models.CharField(blank=True, choices=[('GAP1', 'GAP1'), ('GAP2', 'GAP2'), ('ZTE', 'ZTE')], max_length=255, null=True),
        ),
    ]
