# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0009_auto_20171217_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='ciudad',
            field=models.CharField(choices=[(b'Antioquia', b'Antioquia'), (b'Arauca', b'Arauca'), (b'Atlantico', b'Atlantico'), (b'Barranquilla', b'Barranquilla'), (b'Valle', b'Valle'), (b'Bogota', b'Bogota'), (b'Bolivar', b'Bolivar'), (b'Boyaca', b'Boyaca'), (b'Bucaramanga', b'Bucaramanga'), (b'Caldas', b'Caldas'), (b'Cali', b'Cali'), (b'Cartagena', b'Cartagena'), (b'Cauca', b'Cauca'), (b'Cesar', b'Cesar'), (b'Chia', b'Chia'), (b'Choco', b'Choco'), (b'Cordoba', b'Cordoba'), (b'Cucuta', b'Cucuta'), (b'Cundinamarca', b'Cundinamarca'), (b'Girardot', b'Girardot'), (b'Guajira', b'Guajira'), (b'Huila', b'Huila'), (b'Ibague', b'Ibague'), (b'Magdalena', b'Magdalena'), (b'Medellin', b'Medellin'), (b'Meta', b'Meta'), (b'Norte de Santander', b'Norte de Santander'), (b'Pasto', b'Pasto'), (b'Pereira', b'Pereira'), (b'Popayan', b'Popayan'), (b'Quindio', b'Quindio'), (b'Risaralda', b'Risaralda'), (b'Sincelejo', b'Sincelejo'), (b'Santander', b'Santander'), (b'Soacha', b'Soacha'), (b'Sucre', b'Sucre'), (b'Tolima', b'Tolima'), (b'Tulua', b'Tulua'), (b'Villavicencio', b'Villavicencio'), (b'Putumayo', b'Putumayo'), (b'Manizales', b'Manizales'), (b'Valledupar', b'Valledupar'), (b'Santa Marta', b'Santa Marta'), (b'Zipaquira', b'Zipaquira'), (b'Buenaventura', b'Buenaventura'), (b'Casanare', b'Casanare'), (b'Barranca', b'Barranca'), (b'Ubate', b'Ubate'), (b'Fusagasuga', b'Fusagasuga'), (b'Duitama', b'Duitama'), (b'Sogamoso', b'Sogamoso'), (b'Tunja', b'Tunja'), (b'Yopal', b'Yopal'), (b'Florencia', b'Florencia'), (b'Armenia', b'Armenia'), (b'Valle del Cauca', b'Valle del Cauca'), (b'Jamundi', b'Jamundi')], max_length=255),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='regional',
            field=models.CharField(choices=[(b'Centro', b'Centro'), (b'Costa', b'Costa'), (b'Oriente', b'Oriente'), (b'Occidente', b'Occidente'), (b'Nor Oriente', b'Nor Oriente'), (b'Nor Occidente', b'Nor Occidente'), (b'Sur Oriente', b'Sur Oriente'), (b'Sur Occidente', b'Sur Occidente')], max_length=255),
        ),
    ]
