# Generated by Django 2.0 on 2018-01-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0011_auto_20171224_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='estado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_estacion',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='subestado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
