# Generated by Django 2.0 on 2018-01-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0012_auto_20180125_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='numero_actividades',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
