# -*- coding: utf-8 -*-
""" REGIONAL_CHOICES  """
REGIONAL_CHOICES = (
    ('Centro', 'Centro'),
    ('Costa', 'Costa'),
    ('Oriente', 'Oriente'),
    ('Occidente', 'Occidente'),
    ('Nor Oriente', 'Nor Oriente'),
    ('Nor Occidente', 'Nor Occidente'),
    ('Sur Oriente', 'Sur Oriente'),
    ('Sur Occidente', 'Sur Occidente'),
)

""" CIUDAD_CHOICES  """
CIUDAD_CHOICES = (
    ('Antioquia', 'Antioquia'),
    ('Arauca', 'Arauca'),
    ('Atlantico', 'Atlantico'),
    ('Barranquilla', 'Barranquilla'),
    ('Valle', 'Valle'),
    ('Bogota', 'Bogota'),
    ('Bolivar', 'Bolivar'),
    ('Boyaca', 'Boyaca'),
    ('Bucaramanga', 'Bucaramanga'),
    ('Caldas', 'Caldas'),
    ('Cali', 'Cali'),
    ('Cartagena', 'Cartagena'),
    ('Cauca', 'Cauca'),
    ('Cesar', 'Cesar'),
    ('Chia', 'Chia'),
    ('Choco', 'Choco'),
    ('Cordoba', 'Cordoba'),
    ('Cucuta', 'Cucuta'),
    ('Cundinamarca', 'Cundinamarca'),
    ('Girardot', 'Girardot'),
    ('Guajira', 'Guajira'),
    ('Huila', 'Huila'),
    ('Ibague', 'Ibague'),
    ('Magdalena', 'Magdalena'),
    ('Medellin', 'Medellin'),
    ('Meta', 'Meta'),
    ('Norte de Santander', 'Norte de Santander'),
    ('Pasto', 'Pasto'),
    ('Pereira', 'Pereira'),
    ('Popayan', 'Popayan'),
    ('Quindio', 'Quindio'),
    ('Risaralda', 'Risaralda'),
    ('Sincelejo', 'Sincelejo'),
    ('Santander', 'Santander'),
    ('Soacha', 'Soacha'),
    ('Sucre', 'Sucre'),
    ('Tolima', 'Tolima'),
    ('Tulua', 'Tulua'),
    ('Villavicencio', 'Villavicencio'),
    ('Putumayo', 'Putumayo'),
    ('Manizales', 'Manizales'),
    ('Valledupar', 'Valledupar'),
    ('Santa Marta', 'Santa Marta'),
    ('Zipaquira', 'Zipaquira'),
    ('Buenaventura', 'Buenaventura'),
    ('Casanare', 'Casanare'),
    ('Barranca', 'Barranca'),
    ('Ubate', 'Ubate'),
    ('Fusagasuga', 'Fusagasuga'),
    ('Duitama', 'Duitama'),
    ('Sogamoso', 'Sogamoso'),
    ('Tunja', 'Tunja'),
    ('Yopal', 'Yopal'),
    ('Florencia', 'Florencia'),
    ('Armenia', 'Armenia'),
    ('Valle del Cauca', 'Valle del Cauca'),
    ('Jamundi', 'Jamundi'),
)

""" RESPONSABLE_CHOICES  """
RESPONSABLE_CHOICES = (
    ('GAP1', 'GAP1'),
    ('GAP2', 'GAP2'),
    ('ZTE', 'ZTE'),
)

""" PRIORIDAD_CHOICES  """
PRIORIDAD_CHOICES = (
    ('P1', 'P1'),
)
