# Generated by Django 2.0 on 2018-02-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('agrupadores', models.CharField(blank=True, max_length=255, null=True)),
                ('siteName', models.CharField(blank=True, max_length=80, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=19, null=True)),
                ('banda', models.CharField(blank=True, max_length=30, null=True)),
                ('escenario', models.CharField(blank=True, max_length=20, null=True)),
                ('ss', models.CharField(blank=True, max_length=60, null=True)),
                ('realTiFinish', models.DateField(blank=True, null=True)),
                ('fechaIntegracion', models.DateField(blank=True, null=True)),
                ('fechaEstado', models.DateTimeField(blank=True, null=True)),
                ('estadoNOC', models.CharField(blank=True, max_length=45, null=True)),
                ('subEstadoNOC', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'db_table': 'gi',
                'managed': False,
            },
        ),
    ]
