# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_auto_20171107_1555'),
        ('asignaciones', '0026_auto_20171109_1414'),
        ('actividades', '0040_remove_actividad_responsable'),
        ('estaciones', '0008_auto_20171115_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudHW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('hardware', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(blank=True, choices=[(b'', b'---------'), (b'No requiere', b'No requiere'), (b'Hardware solicitado', b'Hardware solicitado'), (b'Hardware recibido', b'Hardware recibido')], default='No requiere', max_length=255, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('subestado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudeshw', to='actividades.Actividad')),
                ('asignacion_ni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudeshw', to='asignaciones.AsignacionNi')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudeshw', to='estaciones.Estacion')),
                ('ni_ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudeshw', to='users.Perfil')),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'solicitudhw',
                'verbose_name_plural': 'solicitudeshw',
            },
        ),
    ]
