# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudeshw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudhw',
            name='estado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='solicitudhw',
            name='subestado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
