# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudeshw', '0002_auto_20171204_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudhw',
            name='estado_solicitud',
            field=models.CharField(blank=True, choices=[(b'No requiere', b'No requiere'), (b'Hardware solicitado', b'Hardware solicitado'), (b'Hardware recibido', b'Hardware recibido')], default='No requiere', max_length=255, null=True),
        ),
    ]
