# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudeshw', '0004_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
