# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudeshw', '0005_auto_20171205_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudhw',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solicitudhw',
            name='hardware',
        ),
    ]
