# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudeshw', '0009_auto_20171207_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudhw',
            name='estado_solicitud',
            field=models.CharField(blank=True, choices=[(b'Requiere HW', b'Requiere HW'), (b'HW solicitado', b'HW solicitado'), (b'HW recibido', b'HW recibido')], default='Requiere HW', max_length=255, null=True),
        ),
    ]
