# Generated by Django 2.0 on 2018-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudeshw', '0013_auto_20180205_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='serial_desmontado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='serial_nuevo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
