# -*- coding: utf-8 -*-
""" PERFIL_USUARIO_CHOICES  """
PERFIL_USUARIO_CHOICES = (
    ('GAP Administrador', 'GAP Administrador'),
    ('GAP Visitante', 'GAP Visitante'),
    ('NI Ingeniero', 'NI Ingeniero'),
    ('NI Asignador', 'NI Asignador'),
    ('NPO Ingeniero', 'NPO Ingeniero'),
    ('NPO Asignador', 'NPO Asignador'),
    ('FM Lider', 'FM Lider'),
    ('FM Permisos', 'FM Permisos'),
    ('FM Supervisor', 'FM Supervisor'),
    ('GAP Monitoreo', 'GAP Monitoreo'),
)

""" EMPRESA_CHOICES  """
EMPRESA_CHOICES = (
    ('DECOM', 'DECOM'),
    ('INGETEL', 'INGETEL'),
    ('ENECON', 'ENECON'),
    ('NEXPRO', 'NEXPRO'),
    ('JANACOR', 'JANACOR'),
    ('UNION', 'UNION'),
    ('OPTIMACOM', 'OPTIMACOM'),
    ('DELTEC', 'DELTEC'),
    ('FIBRATERRA', 'FIBRATERRA'),
    ('ADSM', 'ADSM'),
    ('SERVINTELCO', 'SERVINTELCO'),
    ('EZENTIS', 'EZENTIS'),
    ('SITCOM', 'SITCOM'),
    ('INGYTELCOM', 'INGYTELCOM'),
    ('SAI', 'SAI'),
    ('GAMMA', 'GAMMA'),
    ('PACIFIC ENERGY', 'PACIFIC ENERGY'),
    ('FUREL', 'FUREL'),
    ('NEOSTAR', 'NEOSTAR'),
    ('DASCON', 'DASCON'),
    ('ATENA', 'ATENA'),
    ('ZOOM', 'ZOOM'),
    ('LINEA', 'LINEA'),
    ('WISECA', 'WISECA'),
    ('REDES Y SERVICIOS', 'REDES Y SERVICIOS'),
    ('NESITELCO', 'NESITELCO'),
    ('NOKIA', 'NOKIA'),
    ('OSC', 'OSC'),
    ('MSI', 'MSI'),
    ('WB INGENIERIA', 'WB INGENIERIA'),
    ('VOLUMEN', 'VOLUMEN'),
    ('INTELCOM', 'INTELCOM'),
    ('ASECONES', 'ASECONES'),
    ('SOI', 'SOI'),
    ('CONECTAR', 'CONECTAR'),
    ('IDT', 'IDT'),
    ('TECHMAHINDRA', 'TECHMAHINDRA'),
    ('ADS INTEGRAL', 'ADS INTEGRAL'),
    ('APPLUS', 'APPLUS'),
    ('CLARO', 'CLARO'),
    ('OIN (CLARO)', 'OIN (CLARO)'),
    ('SFERA', 'SFERA'),
    ('CONSTRUTECH', 'CONSTRUTECH'),
)
