# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0012_auto_20170928_1421'),
        ('users', '0004_auto_20170913_2204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionNi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[(b'No exitosa', b'No exitosa'), (b'Enviado a seguimiento', b'Enviado a seguimiento'), (b'Requiere visita', b'Requiere visita'), (b'En monitoreo', b'En monitoreo')], max_length=255, null=True)),
                ('subestado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni', related_query_name='asignaciones_ni', to='actividades.Actividad')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni', to='estaciones.Estacion')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni', to='users.Perfil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'asignacion ni',
                'verbose_name_plural': 'asignaciones ni',
            },
        ),
        migrations.CreateModel(
            name='AsignacionNpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[(b'No exitosa', b'No exitosa'), (b'Enviado a seguimiento', b'Enviado a seguimiento'), (b'Requiere visita', b'Requiere visita'), (b'En monitoreo', b'En monitoreo')], max_length=255, null=True)),
                ('subestado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo', related_query_name='asignaciones_npo', to='actividades.Actividad')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo', to='estaciones.Estacion')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo', to='users.Perfil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creado',),
                'verbose_name': 'asignacion npo',
                'verbose_name_plural': 'asignaciones npo',
            },
        ),
    ]
