# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170913_2204'),
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionni',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='asignacionni',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asignacionnpo',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='asignacionnpo',
            name='user',
        ),
        migrations.AddField(
            model_name='asignacionni',
            name='ni_asignador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_asignador_ni', to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='asignacionni',
            name='ni_ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ingeniero_ni', to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='npo_asignador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_asignador_npo', to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='npo_ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ingeniero_npo', to='users.Perfil'),
        ),
    ]
