# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_auto_20171002_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
