# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_auto_20171003_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='tipo_intervencion',
            field=models.CharField(blank=True, choices=[(b'Local', b'Local'), (b'Remoto', b'Remoto')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='tipo_intervencion',
            field=models.CharField(blank=True, choices=[(b'Local', b'Local'), (b'Remoto', b'Remoto')], max_length=255, null=True),
        ),
    ]
