# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_auto_20171006_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni', to='actividades.Actividad'),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo', to='actividades.Actividad'),
        ),
    ]
