# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0006_auto_20171009_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='ni_asignador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni_asignador', to='users.Perfil'),
        ),
        migrations.AlterField(
            model_name='asignacionni',
            name='ni_ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni_ingeniero', to='users.Perfil'),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='npo_asignador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo_asignador', to='users.Perfil'),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='npo_ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo_ingeniero', to='users.Perfil'),
        ),
    ]
