# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0007_auto_20171009_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='tipo_intervencion',
            field=models.CharField(blank=True, choices=[(b'', b'---------'), (b'Local', b'Local'), (b'Remoto', b'Remoto')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='tipo_intervencion',
            field=models.CharField(blank=True, choices=[(b'', b'---------'), (b'Local', b'Local'), (b'Remoto', b'Remoto')], max_length=255, null=True),
        ),
    ]
