# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0009_asignacionnpo_posible_causa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionnpo',
            name='posible_causa',
            field=models.CharField(blank=True, choices=[(b'', b'---------'), (b'Instalacion', b'Instalacion'), (b'Software', b'Software'), (b'Hardware', b'Hardware'), (b'Datafill', b'Datafill'), (b'Ajuste Potencia', b'Ajuste Potencia'), (b'Integracion', b'Integracion')], max_length=255, null=True),
        ),
    ]
