# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0010_auto_20171010_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='ni_concepto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='npo_concepto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionni',
            name='estado',
            field=models.CharField(blank=True, choices=[(b'', b'---------'), (b'Asignada', b'Asignada'), (b'No exitosa', b'No exitosa'), (b'Enviado a seguimiento', b'Enviado a seguimiento'), (b'Requiere visita', b'Requiere visita'), (b'En monitoreo', b'En monitoreo')], default='Asignada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='estado',
            field=models.CharField(blank=True, choices=[(b'', b'---------'), (b'Asignada', b'Asignada'), (b'No exitosa', b'No exitosa'), (b'Enviado a seguimiento', b'Enviado a seguimiento'), (b'Requiere visita', b'Requiere visita'), (b'En monitoreo', b'En monitoreo')], default='Asignada', max_length=255, null=True),
        ),
    ]
