# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0013_auto_20171011_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='ni_concepto',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='npo_concepto',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
