# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0016_auto_20171013_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='subestado',
            field=models.BooleanField(default=False),
        ),
    ]
