# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0018_auto_20171016_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='estado_asignacion',
            field=models.CharField(blank=True, choices=[(b'', b'---------'), (b'Asignada', b'Asignada'), (b'No exitosa', b'No exitosa'), (b'Enviado a seguimiento', b'Enviado a seguimiento'), (b'Requiere visita', b'Requiere visita'), (b'En monitoreo', b'En monitoreo'), (b'Escalado a claro', b'Escalado a claro')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='estado_asignacion',
            field=models.CharField(blank=True, choices=[(b'', b'---------'), (b'Asignada', b'Asignada'), (b'No exitosa', b'No exitosa'), (b'Enviado a seguimiento', b'Enviado a seguimiento'), (b'Requiere visita', b'Requiere visita'), (b'En monitoreo', b'En monitoreo'), (b'Escalado a claro', b'Escalado a claro')], max_length=255, null=True),
        ),
    ]
