# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0020_auto_20171016_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
