# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171016_1804'),
        ('asignaciones', '0021_auto_20171016_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='fm_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ni_fm_supervisor', to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='asignacionni',
            name='fm_supervisor_celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asignacionni',
            name='ni_ingeniero_celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='fm_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_npo_fm_supervisor', to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='fm_supervisor_celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='npo_ingeniero_celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
