# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0023_auto_20171027_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='ni_ingeniero_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asignacionnpo',
            name='npo_ingeniero_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
