# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0025_auto_20171027_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='wp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='wp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
