# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0026_auto_20171109_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='ni_estado_solicitud_hw',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
