# Generated by Django 2.0 on 2017-12-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0027_asignacionni_ni_estado_solicitud_hw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='estado_asignacion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Asignada', 'Asignada'), ('En monitoreo', 'En monitoreo'), ('Enviado a seguimiento', 'Enviado a seguimiento'), ('Requiere visita', 'Requiere visita'), ('No exitosa', 'No exitosa'), ('Escalado a claro', 'Escalado a claro')], default='Asignada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionni',
            name='tipo_intervencion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Local', 'Local'), ('Remoto', 'Remoto')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='estado_asignacion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Asignada', 'Asignada'), ('En monitoreo', 'En monitoreo'), ('Enviado a seguimiento', 'Enviado a seguimiento'), ('Requiere visita', 'Requiere visita'), ('No exitosa', 'No exitosa'), ('Escalado a claro', 'Escalado a claro')], default='Asignada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='posible_causa',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Instalacion', 'Instalacion'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Datafill', 'Datafill'), ('Ajuste Potencia', 'Ajuste Potencia'), ('Integracion', 'Integracion'), ('Interferencia externa', 'Interferencia externa'), ('Cambio diseno', 'Cambio diseno'), ('Mal rechazo', 'Mal rechazo'), ('Otra causa', 'Otra causa')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='tipo_intervencion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Local', 'Local'), ('Remoto', 'Remoto')], max_length=255, null=True),
        ),
    ]
