# Generated by Django 2.0 on 2017-12-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0028_auto_20171217_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionnpo',
            name='posible_causa',
        ),
        migrations.AddField(
            model_name='asignacionni',
            name='origen_falla',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Instalacion', 'Instalacion'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Datafill', 'Datafill'), ('Ajuste Potencia', 'Ajuste Potencia'), ('Integracion', 'Integracion'), ('Interferencia externa', 'Interferencia externa'), ('Cambio diseno', 'Cambio diseno'), ('Mal rechazo', 'Mal rechazo'), ('Otra causa', 'Otra causa')], max_length=255, null=True),
        ),
    ]
