# Generated by Django 2.0 on 2018-01-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0029_auto_20171224_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='estado_asignacion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Asignada', 'Asignada'), ('En monitoreo', 'En monitoreo'), ('Enviado a seguimiento', 'Enviado a seguimiento'), ('Requiere visita', 'Requiere visita'), ('Escalado a claro', 'Escalado a claro')], default='Asignada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionnpo',
            name='estado_asignacion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Asignada', 'Asignada'), ('En monitoreo', 'En monitoreo'), ('Enviado a seguimiento', 'Enviado a seguimiento'), ('Requiere visita', 'Requiere visita'), ('Escalado a claro', 'Escalado a claro')], default='Asignada', max_length=255, null=True),
        ),
    ]
