# Generated by Django 2.0 on 2018-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0030_auto_20180109_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='solver',
            field=models.CharField(blank=True, choices=[('NOKIA', 'NOKIA'), ('SERVICE SUPPLIER', 'SERVICE SUPPLIER')], max_length=255, null=True),
        ),
    ]
