# Generated by Django 2.0 on 2018-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0031_asignacionni_solver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='solver',
            field=models.CharField(blank=True, choices=[('', '---------'), ('NOKIA', 'NOKIA'), ('SERVICE SUPPLIER', 'SERVICE SUPPLIER')], max_length=255, null=True),
        ),
    ]
