# Generated by Django 2.0 on 2018-01-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0032_auto_20180109_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionni',
            name='solver',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Nokia', 'Nokia'), ('Service suplier', 'Service suplier')], max_length=255, null=True),
        ),
    ]
