# Generated by Django 2.0 on 2018-01-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0034_asignacionni_detalle_falla_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='asignar_par',
            field=models.BooleanField(default=False),
        ),
    ]
