# Generated by Django 2.0 on 2018-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0042_auto_20180604_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionni',
            name='detalle_falla_hardware',
            field=models.TextField(blank=True, null=True),
        ),
    ]
